from __future__ import annotations

from typing import Any, Optional, Protocol


class AudioBackend(Protocol):
    def close(self) -> None: ...

    def play_music_file(self, path: str, volume: float = 1.0, start_pos_sec: float = 0.0) -> None: ...
    def stop_music(self) -> None: ...
    def pause_music(self) -> None: ...
    def unpause_music(self) -> None: ...
    def music_pos_sec(self) -> Optional[float]: ...

    def load_sound(self, path: str) -> Any: ...
    def play_sound(self, sound: Any, volume: float = 1.0) -> Any: ...
    def stop_channel(self, channel: Any) -> None: ...
